services:
  db:
    image: mysql:8.4
    container_name: habitora_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: habitora
      MYSQL_USER: habitora
      MYSQL_PASSWORD: secret
      TZ: America/Lima
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootsecret || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: habitora
      PMA_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy

  # app:
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile
  #   container_name: habitora_app
  #   restart: unless-stopped
  #   environment:
  #     SPRING_PROFILES_ACTIVE: prod
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/habitora?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #     SPRING_DATASOURCE_USERNAME: habitora
  #     SPRING_DATASOURCE_PASSWORD: secret
  #     SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  #     TZ: America/Lima
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     db:
  #       condition: service_healthy

volumes:
  mysql_data:
